# Generated by Django 5.2.6 on 2025-10-23 10:41

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Необязательное поле', max_length=128, null=True, region='RU', verbose_name='Номер телефона'),
        ),
    ]
