# Generated by Django 5.2.6 on 2025-10-23 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogpost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок статьи')),
                ('content', models.TextField(verbose_name='Содержание статьи')),
                ('preview', models.ImageField(blank=True, default='products/images/default.png', null=True, upload_to='blog/images/', verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения')),
                ('status', models.CharField(choices=[('moderation', 'На модерации'), ('published', 'Опубликовано'), ('archived', 'В архиве')], default='moderation', max_length=20, verbose_name='Статус')),
                ('number_of_views', models.PositiveIntegerField(default=0, verbose_name='Количество просмотров')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'блоговый пост',
                'verbose_name_plural': 'блоговые посты',
                'ordering': ['created_at'],
            },
        ),
    ]
