# Generated by Django 5.2.6 on 2025-10-25 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['created_at'], 'permissions': [('can_publish_blogpost', 'Can publish blogpost'), ('can_unpublish_blogpost', 'Can unpublish blogpost')], 'verbose_name': 'блоговый пост', 'verbose_name_plural': 'блоговые посты'},
        ),
    ]
