# Generated by Django 5.2.6 on 2025-10-10 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blogpost_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='number_of_views',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество просмотров'),
        ),
    ]
