# Generated by Django 5.2.6 on 2025-10-16 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_delete_author_alter_blogpost_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='preview',
            field=models.ImageField(blank=True, default='images/default.png', null=True, upload_to='blog/images/', verbose_name='Изображение'),
        ),
    ]
