# Generated by Django 5.2.6 on 2025-10-17 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_blogpost_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='preview',
            field=models.ImageField(blank=True, default='products/images/default.png', null=True, upload_to='blog/images/', verbose_name='Изображение'),
        ),
    ]
