# Generated by Django 5.2.6 on 2025-09-25 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=20, verbose_name='Страна')),
                ('address', models.CharField(max_length=150, verbose_name='Юридический адрес')),
                ('email', models.EmailField(max_length=50, verbose_name='Адрес электронной почты')),
            ],
            options={
                'verbose_name': 'контакты',
                'verbose_name_plural': 'контакты',
                'ordering': ['country', 'address'],
            },
        ),
    ]
