# Generated by Django 5.2.6 on 2025-09-27 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_messagefeedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagefeedback',
            name='phone',
            field=models.CharField(max_length=15, verbose_name='Номер телефона пользователя'),
        ),
    ]
