# Generated by Django 5.2.6 on 2025-10-15 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_alter_product_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messagefeedback',
            options={'ordering': ['name', 'email', 'created_at'], 'verbose_name': 'обратная связь', 'verbose_name_plural': 'обратная связь'},
        ),
        migrations.RemoveField(
            model_name='messagefeedback',
            name='phone',
        ),
        migrations.AddField(
            model_name='messagefeedback',
            name='email',
            field=models.EmailField(default='test@mail.ru', max_length=254, verbose_name='E-mail пользователя'),
        ),
        migrations.AlterField(
            model_name='messagefeedback',
            name='message',
            field=models.TextField(max_length=2000, verbose_name='Сообщение пользователя'),
        ),
    ]
