# Generated by Django 5.2.6 on 2025-10-15 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_alter_messagefeedback_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagefeedback',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-mail пользователя'),
        ),
    ]
