# Generated by Django 5.2.6 on 2025-10-15 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_alter_messagefeedback_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brief_description',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Краткое описание товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(help_text='Введите цену в формате 00.0', verbose_name='Цена товара'),
        ),
    ]
