# Generated by Django 5.2.6 on 2025-10-17 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='static/images/default.png', null=True, upload_to='products/images/', verbose_name='Изображение'),
        ),
    ]
