# Generated by Django 5.2.6 on 2025-10-17 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='products/images/default.png', null=True, upload_to='products/images/', verbose_name='Изображение'),
        ),
    ]
