# Generated by Django 5.2.6 on 2025-10-25 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_alter_messagefeedback_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacts',
            options={'ordering': ['country', 'address'], 'permissions': [('can_publish_product', 'Can publish product'), ('can_unpublish_product', 'Can unpublish product')], 'verbose_name': 'контакты', 'verbose_name_plural': 'контакты'},
        ),
        migrations.AlterModelOptions(
            name='messagefeedback',
            options={'ordering': ['name', 'email', 'created_at'], 'verbose_name': 'обратная связь', 'verbose_name_plural': 'обратная связь'},
        ),
    ]
