# Generated by Django 5.2.6 on 2025-10-25 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_alter_contacts_options_alter_messagefeedback_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacts',
            options={'ordering': ['country', 'address'], 'verbose_name': 'контакты', 'verbose_name_plural': 'контакты'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'permissions': [('can_publish_product', 'Can publish product'), ('can_unpublish_product', 'Can unpublish product')], 'verbose_name': 'товар', 'verbose_name_plural': 'товары'},
        ),
    ]
